export const QUEUE_MODULE_LISTENER = "QUEUE_MODULE_LISTENER";
export const QUEUE_MODULE_PROCESSOR = "QUEUE_MODULE_PROCESSOR";
export const QUEUE_MODULE_PROCESS = "QUEUE_MODULE_PROCESS";
export const QUEUE_MODULE_JOBS_STORAGE = "QUEUE_MODULE_JOBS_STORAGE";

export const QUEUE_MODULE_OPTIONS = "QUEUE_MODULE_OPTIONS";

export const QUEUE_MODULE_QUEUE_OPTIONS = "QUEUE_MODULE_QUEUE_OPTIONS";

export const QUEUE_MODULE_DEFAULT_PROCESSOR = "default";
export const QUEUE_MODULE_DEFAULT_PROCESS = "default";
