export enum StorageGatewayEventsEnum {
  ON_NEW_ENTITY_DETECTED = "ON_NEW_ENTITY_DETECTED",
  ON_NEW_ENTITY_UPLOADED = "ON_NEW_ENTITY_UPLOADED",
  ON_NEW_ENTITY_UPLOAD_PROGRESS = "ON_NEW_ENTITY_UPLOAD_PROGRESS",
}
